version: '3.7'
services:
    nginx:
        image: nginx:latest
        ports:
            - target: 80
              published: 80
              protocol: tcp
        volumes:
            - jenkins_nginx_vol:/var/jenkins_home/workspace/quad-base/
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
        depends_on:
            - server
            - client        
            - mongo
    server:
        image: localhost:5000/server:latest
        build:
            context: ./server   
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
        depends_on:
            - mongo
    client:
        image: localhost:5000/client:latest
        build:
            context: ./client
        ports:
            - target: 3000
              published: 3000
              protocol: tcp      
        environment:
            - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - target: 27017
              published: 27017
              protocol: tcp
    mongo-seed:
        image: fvilers/mongo-seed:1.0.0
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
        volumes:
            - ./data:/data
        command:
            - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"
volumes:
    jenkins_nginx_vol:
